print("ingrédient pour faire une fondue fribourgeoise")
print()
inv=int(input("Entrez le nombre de personne(s) conviées à la fondue: "))
print("pour",inv,"conviées, il vous faudra :")
print("-",800.0*inv/4,"gr fromage")
print("-",2*inv/4,"eau")
print("-",2*inv/4,"ail")
print("-",400*inv/4,"gr pain")
